language: scala
scala:
  - 2.12.8
jdk:
  - openjdk11

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

before_install:
  - git fetch --tags

stages:
  - name: test

jobs:
  include:
    - stage: test
      script:
      - sbt clean test # compile and run tests

cache:
  directories:
    - "/tmp/embedded-keycloak/"
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot