language: scala
scala:
  - 2.12.8
jdk:
  - oraclejdk8

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

before_install:
  - git fetch --tags

stages:
  - name: test
#  - name: release
#    if: tag IS present

jobs:
  include:
    - stage: test
      script:
      - sbt clean test # compile and run tests
#      - sbt coverageReport coverageAggregate # create coverage reports
#      - sbt coveralls codacyCoverage # upload coverage to coveralls and codacy
#    - stage: release
#      script:
#      - sbt ci-release

cache:
  directories:
    - "/tmp/embedded-keycloak/"
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot